-- Custom SQL migration file, put your code below!
-- Vercel/Supabase compatibility: BM25 indexes require the pg_search extension.
-- pg_search is not available on managed PostgreSQL used by this deployment,
-- so this optional full-text/BM25 optimization is intentionally skipped.
