import { CopyButton, Flexbox } from '@lobehub/ui';
import { ActionIcon } from '@lobehub/ui/base-ui';
import { createStaticStyles } from 'antd-style';
import { Eye, EyeOff } from 'lucide-react';
import { type FC, useState } from 'react';
import { useTranslation } from 'react-i18next';

const styles = createStaticStyles(({ css, cssVar }) => ({
  key: css`
    overflow: hidden;

    font-family: ${cssVar.fontFamilyCode};
    font-size: 12px;
    text-overflow: ellipsis;
    white-space: nowrap;
  `,
}));

interface ApiKeyDisplayProps {
  apiKey?: string;
}

/** Bullet run standing in for the hidden middle of the key. */
const MASK = '••••••••';

const ApiKeyDisplay: FC<ApiKeyDisplayProps> = ({ apiKey }) => {
  const { t } = useTranslation('auth');
  const [isVisible, setIsVisible] = useState(false);

  if (!apiKey) {
    return t('apikey.display.autoGenerated');
  }

  // Mask keeps the key's real prefix (e.g. `sk-lh-`) and its last 4 characters
  // so rows stay tellable apart while hidden; fall back to a full mask for
  // keys too short to safely reveal a tail.
  const prefixLength = apiKey.lastIndexOf('-') + 1;
  const prefix = apiKey.slice(0, prefixLength);
  const canShowTail = apiKey.length - prefixLength > 8;
  const displayValue = isVisible
    ? apiKey
    : canShowTail
      ? `${prefix}${MASK}${apiKey.slice(-4)}`
      : `${prefix}${MASK}`;

  return (
    <Flexbox horizontal align={'center'} gap={4}>
      <span className={styles.key}>{displayValue}</span>
      <ActionIcon
        icon={isVisible ? EyeOff : Eye}
        size={'small'}
        title={isVisible ? t('apikey.display.hide') : t('apikey.display.show')}
        onClick={() => setIsVisible(!isVisible)}
      />
      <CopyButton content={apiKey} size={'small'} title={t('apikey.display.copy')} />
    </Flexbox>
  );
};

export default ApiKeyDisplay;
