lockfile: false
packages:
  - packages/**
  - .
  - e2e
  - apps/desktop/src/main
  - apps/auth
  - apps/server
  - apps/share
  - apps/workbench

minimumReleaseAgeExclude:
  - '@lobehub/ui@5.20.2'

onlyBuiltDependencies:
  - '@google/genai'
  - '@lobehub/editor'
  - '@vercel/speed-insights'

overrides:
  jose: ^6.1.3
  stylelint-config-clean-order: 7.0.0
  pdfjs-dist: 5.4.530
  react: 19.2.4
  react-dom: 19.2.4
  '@react-pdf/image': 3.0.4

patchedDependencies:
  '@upstash/qstash': patches/@upstash__qstash.patch
