export const OPENAI_END_POINT = 'X-OPENAI-END_POINT';

export const OPENAI_API_KEY_HEADER_KEY = 'X-OPENAI-API-KEY';

export const LOBE_CHAT_ACCESS_CODE = 'X-LOBE_CHAT_ACCESS_CODE';

export const LOBE_PLUGIN_SETTINGS = 'X-LOBE_PLUGIN_SETTINGS';
