import type { PartialDeep } from 'type-fest';
import { z } from 'zod';

import type { LobeToolRenderType } from '../../tool';

// ToolIntervention must be defined first to avoid circular dependency
export interface ToolIntervention {
  /** Stable sealed batch id, bound to one parked operation + assistant turn. */
  batchId?: string;
  /** Declaration order inside the sealed batch. */
  itemIndex?: number;
  /** Parked runtime operation this decision must resume or stop. */
  operationId?: string;
  rejectedReason?: string;
  /** Server-minted idempotency/rollback owner for an authoritative resolution. */
  resolutionRequestId?: string;
  /** User decision published, awaiting the blocked producer's ACK. */
  resolving?: boolean;
  /**
   * The user skipped the interaction (e.g. AskUserQuestion) rather than
   * rejecting the tool call — still `status: 'rejected'` for the runtime, but
   * the UI renders a neutral "skipped" state instead of a rejection warning.
   */
  skipped?: boolean;
  status?: 'pending' | 'approved' | 'rejected' | 'aborted' | 'none';
  stepIndex?: number;
}

export const ToolInterventionSchema = z.object({
  batchId: z.string().optional(),
  itemIndex: z.number().int().nonnegative().optional(),
  operationId: z.string().optional(),
  rejectedReason: z.string().optional(),
  resolving: z.boolean().optional(),
  resolutionRequestId: z.string().optional(),
  skipped: z.boolean().optional(),
  stepIndex: z.number().int().nonnegative().optional(),
  status: z.enum(['pending', 'approved', 'rejected', 'aborted', 'none']).optional(),
});

export interface ChatPluginPayload {
  apiName: string;
  arguments: string;
  identifier: string;
  intervention?: ToolIntervention;
  type: LobeToolRenderType;
}

/**
 * Tool source indicates where the tool comes from
 */
export type ToolSource = 'builtin' | 'client' | 'mcp' | 'composio' | 'lobehubSkill';

/**
 * Tool executor indicates where the tool is executed for a given invocation.
 * Orthogonal to ToolSource (origin): executor describes dispatch target.
 */
export type ToolExecutor = 'client' | 'server';

export interface ChatToolPayload {
  apiName: string;
  arguments: string;
  /**
   * Tool executor: dispatch target for this invocation.
   */
  executor?: ToolExecutor;
  id: string;
  identifier: string;
  intervention?: ToolIntervention;
  result_msg_id?: string;
  /**
   * Tool source indicates where the tool comes from
   */
  source?: ToolSource;
  thoughtSignature?: string;
  type: LobeToolRenderType;
}

/**
 * Tool execution result from tool messages
 */
export interface ChatToolResult {
  content: string | null;
  error?: any;
  id: string;
  state?: any;
}

/**
 * Internal conditional-write descriptor for a heterogeneous tool-state
 * snapshot. It is not part of the renderer-facing pluginState payload.
 */
export interface HeterogeneousToolStateSnapshot {
  operationId: string;
  snapshotSeq: number;
}

/**
 * Chat tool payload with merged execution result
 */
export interface ChatToolPayloadWithResult extends ChatToolPayload {
  intervention?: ToolIntervention;
  result?: ChatToolResult;
  result_msg_id?: string;
}

export interface ToolsCallingContext {
  topicId?: string;
}
/**
 * The function that the model called.
 */
export interface ToolFunction {
  /**
   * The arguments to call the function with, as generated by the model in JSON
   * format. Note that the model does not always generate valid JSON, and may
   * hallucinate parameters not defined by your function schema. Validate the
   * arguments in your code before calling your function.
   */
  arguments: string;

  /**
   * The name of the function to call.
   */
  name: string;
}

export interface MessageToolCall {
  /**
   * The function that the model called.
   */
  function: ToolFunction;

  /**
   * The ID of the tool call.
   */
  id: string;

  thoughtSignature?: string;
  /**
   * The type of the tool. Currently, only `function` is supported.
   */
  type: 'function' | string;
}

export type MessageToolCallChunk = PartialDeep<MessageToolCall> & { index: number };

export const MessageToolCallSchema = z.object({
  function: z.object({
    arguments: z.string(),
    name: z.string(),
  }),
  id: z.string(),
  type: z.string(),
});

export const ChatToolPayloadSchema = z.object({
  apiName: z.string(),
  arguments: z.string(),
  id: z.string(),
  identifier: z.string(),
  intervention: ToolInterventionSchema.optional(),
  result_msg_id: z.string().optional(),
  thoughtSignature: z.string().optional(),
  type: z.string(),
});

/**
 * Chat message error object
 */
export interface ChatMessagePluginError {
  body?: any;
  message: string;
  type: string;
}
