import { createStyles } from '@/mobile/theme';

export const useStyles = createStyles((token, backgroundColor?: string) => ({
  avatarContainer: {
    backgroundColor: backgroundColor || token.colorBgElevated,
    borderRadius: token.borderRadiusLG * 2.75,
    marginBottom: token.marginSM,
    marginTop: token.marginXS,
    padding: token.paddingXXS,
  },
  avatarEmoji: {
    fontSize: token.fontSizeHeading1 * 2.5,
    textAlign: 'center',
  },
  avatarImg: {
    borderRadius: 36,
    height: 72,
    width: 72,
  },
  avatarWrapper: {
    alignItems: 'center',
    backgroundColor: token.colorBgContainer,
    borderRadius: 36,
    height: 72,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 72,
  },
  container: {
    backgroundColor: token.colorBgLayout,
    flex: 1,
  },
  description: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeLG,
    lineHeight: token.lineHeightLG * token.fontSizeLG,
    marginBottom: token.marginSM,
    paddingHorizontal: token.paddingLG,
    textAlign: 'center',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    height: token.controlHeight,
    marginBottom: token.marginSM,
    paddingHorizontal: token.paddingSM,
    width: '100%',
  },
  historyRow: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: token.borderRadius,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: token.marginXXS,
    paddingHorizontal: token.paddingXXS,
    paddingVertical: token.paddingXS,
  },
  historySection: {
    alignSelf: 'stretch',
    marginHorizontal: token.margin,
    marginTop: token.margin,
  },
  historyText: {
    color: token.colorPrimary,
    flex: 1,
    fontSize: token.fontSize,
    fontWeight: `${token.fontWeight}` as any,
    textAlign: 'left',
  },
  historyTime: {
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    marginLeft: token.marginSM,
    minWidth: 44,
    textAlign: 'right',
  },
  historyTitle: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeLG,
    fontWeight: `${token.fontWeight}` as any,
    marginBottom: token.marginXS,
    marginLeft: token.marginXXS,
  },
  tag: {
    backgroundColor: token.colorBgContainer,
    borderColor: token.colorBorder,
    borderRadius: token.borderRadius,
    borderWidth: 1,
    margin: token.marginXXS,
    paddingHorizontal: token.paddingSM,
    paddingVertical: token.paddingXXS,
  },
  tagText: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: token.marginXS,
    justifyContent: 'center',
    marginBottom: token.margin,
    marginTop: token.marginXXS,
  },
  title: {
    color: token.colorTextHeading,
    fontSize: token.fontSizeHeading3,
    fontWeight: token.fontWeightStrong,
    marginBottom: token.marginXS,
    marginTop: token.marginXXS,
    textAlign: 'center',
  },
}));
