export const DEBUG_CHAT_COMPLETION = process.env.DEBUG_CHAT_COMPLETION === '1';
export const DEBUG_OPENAI_CHAT_COMPLETION = process.env.DEBUG_OPENAI_CHAT_COMPLETION === '1';
export const DEBUG_ZHIPU_CHAT_COMPLETION = process.env.DEBUG_ZHIPU_CHAT_COMPLETION === '1';
