import _taggedTemplateLiteral from "@babel/runtime/helpers/esm/taggedTemplateLiteral";
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14, _templateObject15;
import { createStyles } from 'antd-style';
import { rgba } from 'polished';
export var useStyles = createStyles(function (_ref, _ref2) {
  var token = _ref.token,
    isDarkMode = _ref.isDarkMode,
    css = _ref.css;
  var _ref2$fontSize = _ref2.fontSize,
    fontSize = _ref2$fontSize === void 0 ? 16 : _ref2$fontSize,
    _ref2$headerMultiple = _ref2.headerMultiple,
    headerMultiple = _ref2$headerMultiple === void 0 ? 1 : _ref2$headerMultiple,
    _ref2$marginMultiple = _ref2.marginMultiple,
    marginMultiple = _ref2$marginMultiple === void 0 ? 1.5 : _ref2$marginMultiple,
    _ref2$lineHeight = _ref2.lineHeight,
    lineHeight = _ref2$lineHeight === void 0 ? 1.8 : _ref2$lineHeight;
  return {
    __root: css(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n        --lobe-markdown-font-size: ", "px;\n        --lobe-markdown-header-multiple: ", ";\n        --lobe-markdown-margin-multiple: ", ";\n        --lobe-markdown-line-height: ", ";\n        --lobe-markdown-border-radius: ", ";\n        --lobe-markdown-border-color: ", ";\n\n        position: relative;\n\n        width: 100%;\n        padding-inline: 1px;\n\n        font-size: var(--lobe-markdown-font-size);\n        line-height: var(--lobe-markdown-line-height);\n        word-break: break-word;\n      "])), fontSize, headerMultiple, marginMultiple, lineHeight, token.borderRadiusLG, isDarkMode ? token.colorBorderSecondary : rgba(token.colorBorderSecondary, 0.5)),
    a: css(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["\n        a {\n          color: ", ";\n\n          &:hover {\n            color: ", ";\n          }\n        }\n      "])), token.colorInfoText, token.colorInfoHover),
    blockquote: css(_templateObject3 || (_templateObject3 = _taggedTemplateLiteral(["\n        blockquote {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          margin-inline: 0;\n          padding-block: 0;\n          padding-inline: 1em;\n\n          color: ", ";\n\n          border-inline-start: solid 4px ", ";\n        }\n      "])), token.colorTextSecondary, token.colorBorder),
    code: css(_templateObject4 || (_templateObject4 = _taggedTemplateLiteral(["\n        code:not(:has(span)) {\n          display: inline;\n\n          margin-inline: 0.25em;\n          padding-block: 0.2em;\n          padding-inline: 0.4em;\n\n          font-family: ", ";\n          font-size: 0.875em;\n          line-height: 1;\n          word-break: break-word;\n          white-space: break-spaces;\n\n          background: ", ";\n          border: 1px solid var(--lobe-markdown-border-color);\n          border-radius: 0.25em;\n        }\n      "])), token.fontFamilyCode, token.colorFillSecondary),
    details: css(_templateObject5 || (_templateObject5 = _taggedTemplateLiteral(["\n        details {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          padding-block: 0.75em;\n          padding-inline: 1em;\n\n          background: ", ";\n          border-radius: calc(var(--lobe-markdown-border-radius) * 1px);\n          box-shadow: 0 0 0 1px var(--lobe-markdown-border-color);\n\n          summary {\n            cursor: pointer;\n            display: flex;\n            align-items: center;\n            list-style: none;\n\n            &::before {\n              content: '';\n\n              position: absolute;\n              inset-inline-end: 1.25em;\n              transform: rotateZ(-45deg);\n\n              display: block;\n\n              width: 0.4em;\n              height: 0.4em;\n\n              font-family: ", ";\n\n              border-block-end: 1.5px solid ", ";\n              border-inline-end: 1.5px solid ", ";\n\n              transition: transform 200ms ", ";\n            }\n          }\n\n          &[open] {\n            summary {\n              padding-block-end: 0.75em;\n              border-block-end: 1px dashed ", ";\n\n              &::before {\n                transform: rotateZ(45deg);\n              }\n            }\n          }\n        }\n      "])), token.colorFillTertiary, token.fontFamily, token.colorTextSecondary, token.colorTextSecondary, token.motionEaseOut, token.colorBorder),
    header: css(_templateObject6 || (_templateObject6 = _taggedTemplateLiteral(["\n        h1,\n        h2,\n        h3,\n        h4,\n        h5,\n        h6 {\n          margin-block: max(\n            calc(\n              var(--lobe-markdown-header-multiple) * var(--lobe-markdown-margin-multiple) * 0.4em\n            ),\n            var(--lobe-markdown-font-size)\n          );\n          font-weight: bold;\n          line-height: 1.25;\n        }\n\n        h1 {\n          font-size: calc(\n            var(--lobe-markdown-font-size) * (1 + 1.5 * var(--lobe-markdown-header-multiple))\n          );\n        }\n\n        h2 {\n          font-size: calc(\n            var(--lobe-markdown-font-size) * (1 + var(--lobe-markdown-header-multiple))\n          );\n        }\n\n        h3 {\n          font-size: calc(\n            var(--lobe-markdown-font-size) * (1 + 0.5 * var(--lobe-markdown-header-multiple))\n          );\n        }\n\n        h4 {\n          font-size: calc(\n            var(--lobe-markdown-font-size) * (1 + 0.25 * var(--lobe-markdown-header-multiple))\n          );\n        }\n\n        h5,\n        h6 {\n          font-size: calc(var(--lobe-markdown-font-size) * 1);\n        }\n      "]))),
    hr: css(_templateObject7 || (_templateObject7 = _taggedTemplateLiteral(["\n        hr {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1.5em);\n\n          border-color: ", ";\n          border-style: dashed;\n          border-width: 1px;\n          border-block-start: none;\n          border-inline-start: none;\n          border-inline-end: none;\n        }\n      "])), token.colorBorderSecondary),
    img: css(_templateObject8 || (_templateObject8 = _taggedTemplateLiteral(["\n        img {\n          max-width: 100%;\n        }\n\n        > img,\n        > p > img {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          border-radius: calc(var(--lobe-markdown-border-radius) * 1px);\n          box-shadow: 0 0 0 1px var(--lobe-markdown-border-color);\n        }\n      "]))),
    kbd: css(_templateObject9 || (_templateObject9 = _taggedTemplateLiteral(["\n        kbd {\n          cursor: default;\n\n          display: inline-block;\n\n          min-width: 1em;\n          margin-inline: 0.25em;\n          padding-block: 0.2em;\n          padding-inline: 0.4em;\n\n          font-family: ", ";\n          font-size: 0.875em;\n          font-weight: 500;\n          line-height: 1;\n          text-align: center;\n\n          background: ", ";\n          border: 1px solid ", ";\n          border-radius: 0.25em;\n        }\n      "])), token.fontFamily, token.colorBgLayout, token.colorBorderSecondary),
    list: css(_templateObject10 || (_templateObject10 = _taggedTemplateLiteral(["\n        li {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 0.33em);\n        }\n\n        ul,\n        ol {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          margin-inline-start: 1em;\n          padding-inline-start: 0;\n          list-style-position: outside;\n\n          ul,\n          ol {\n            margin-block: 0;\n          }\n\n          li {\n            margin-inline-start: 1em;\n          }\n        }\n\n        ol {\n          list-style: auto;\n        }\n\n        ul {\n          list-style-type: none;\n\n          li {\n            &::before {\n              content: '-';\n              display: inline-block;\n              margin-inline: -1em 0.5em;\n              opacity: 0.5;\n            }\n          }\n        }\n      "]))),
    p: css(_templateObject11 || (_templateObject11 = _taggedTemplateLiteral(["\n        p {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          line-height: var(--lobe-markdown-line-height);\n          letter-spacing: 0.02em;\n        }\n      "]))),
    pre: css(_templateObject12 || (_templateObject12 = _taggedTemplateLiteral(["\n        pre,\n        [data-code-type='highlighter'] {\n          white-space: break-spaces;\n          border: none;\n\n          > code {\n            padding: 0 !important;\n\n            font-family: ", ";\n            font-size: 0.875em;\n            line-height: 1.6;\n\n            border: none !important;\n          }\n        }\n      "])), token.fontFamilyCode),
    strong: css(_templateObject13 || (_templateObject13 = _taggedTemplateLiteral(["\n        strong {\n          font-weight: 600;\n        }\n      "]))),
    table: css(_templateObject14 || (_templateObject14 = _taggedTemplateLiteral(["\n        table {\n          overflow: auto hidden;\n          display: block;\n          border-spacing: 0;\n          border-collapse: collapse;\n\n          box-sizing: border-box;\n          width: fit-content;\n          max-width: 100%;\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n\n          text-align: start;\n          text-wrap: balance;\n          word-break: auto-phrase;\n          overflow-wrap: break-word;\n\n          background: ", ";\n          border-radius: calc(var(--lobe-markdown-border-radius) * 1px);\n          box-shadow: 0 0 0 1px var(--lobe-markdown-border-color);\n\n          code {\n            word-break: break-word;\n          }\n\n          thead {\n            background: ", ";\n          }\n\n          tr {\n            box-shadow: 0 1px 0 var(--lobe-markdown-border-color);\n          }\n\n          th,\n          td {\n            padding-block: 0.75em;\n            padding-inline: 1em;\n            text-align: start;\n          }\n        }\n      "])), token.colorFillQuaternary, token.colorFillQuaternary),
    video: css(_templateObject15 || (_templateObject15 = _taggedTemplateLiteral(["\n        > video,\n        > p > video {\n          margin-block: calc(var(--lobe-markdown-margin-multiple) * 1em);\n          border-radius: calc(var(--lobe-markdown-border-radius) * 1px);\n          box-shadow: 0 0 0 1px var(--lobe-markdown-border-color);\n        }\n\n        video {\n          max-width: 100%;\n        }\n      "])))
  };
});