import { AIChatModelCard } from '@/types/aiModel';

const aihubmixModels: AIChatModelCard[] = [
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 65_536,
    description: 'DeepSeek R1 推理模型，具有强大的推理能力',
    displayName: 'DeepSeek R1',
    enabled: true,
    id: 'DeepSeek-R1',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 200_000,
    description: 'Claude Opus 4 最新版本，具有卓越的推理和创作能力',
    displayName: 'Claude Opus 4',
    enabled: true,
    id: 'claude-opus-4-20250514',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 200_000,
    description: 'Claude Sonnet 4 最新版本，平衡性能与效率',
    displayName: 'Claude Sonnet 4',
    enabled: true,
    id: 'claude-sonnet-4-20250514',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: 'Gemini 2.5 Flash 预览版，快速高效的多模态模型',
    displayName: 'Gemini 2.5 Flash',
    enabled: true,
    id: 'gemini-2.5-flash-preview-05-20',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: 'Gemini 2.5 Flash 无思维链版本',
    displayName: 'Gemini 2.5 Flash (No Think)',
    enabled: true,
    id: 'gemini-2.5-flash-preview-05-20-nothink',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: 'Gemini 2.5 Flash 搜索增强版本',
    displayName: 'Gemini 2.5 Flash (Search)',
    enabled: true,
    id: 'gemini-2.5-flash-preview-05-20-search',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 200_000,
    description: 'OpenAI o3 推理模型，具有强大的推理能力',
    displayName: 'o3',
    enabled: true,
    id: 'o3',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 200_000,
    description: 'OpenAI o4-mini 小型推理模型，高效且经济',
    displayName: 'o4-mini',
    enabled: true,
    id: 'o4-mini',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_047_576,
    description: 'GPT-4.1 旗舰模型，适用于复杂任务',
    displayName: 'GPT-4.1',
    enabled: true,
    id: 'gpt-4.1',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_047_576,
    description: 'GPT-4.1 mini 平衡智能、速度和成本',
    displayName: 'GPT-4.1 mini',
    enabled: true,
    id: 'gpt-4.1-mini',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description: 'Gemini 2.5 Flash 预览版 (04-17)',
    displayName: 'Gemini 2.5 Flash (04-17)',
    enabled: true,
    id: 'gemini-2.5-flash-preview-04-17',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 2_000_000,
    description: 'Gemini 2.5 Pro 预览版，长上下文支持',
    displayName: 'Gemini 2.5 Pro',
    enabled: true,
    id: 'gemini-2.5-pro-preview-05-06',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
    },
    contextWindowTokens: 235_000,
    description: 'Qwen3 235B 大型语言模型',
    displayName: 'Qwen3 235B',
    enabled: true,
    id: 'Qwen/Qwen3-235B-A22B',
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
    },
    contextWindowTokens: 32_000,
    description: 'Qwen3 32B 中型语言模型',
    displayName: 'Qwen3 32B',
    enabled: true,
    id: 'Qwen/Qwen3-32B',
    type: 'chat',
  },
];

export default aihubmixModels;
