import { AIChatModelCard } from '@/types/aiModel';

const cometapiChatModels: AIChatModelCard[] = [
  {
    description: 'GPT-5 最新版本，具有强大的推理和对话能力',
    displayName: 'gpt-5-chat-latest',
    enabled: true,
    id: 'gpt-5-chat-latest',
    type: 'chat',
  },
  {
    description: 'ChatGPT-4o 最新版本，多模态能力强',
    displayName: 'chatgpt-4o-latest',
    enabled: true,
    id: 'chatgpt-4o-latest',
    type: 'chat',
  },
  {
    description: 'GPT-5 Mini 版本，经济实用',
    displayName: 'gpt-5-mini',
    enabled: true,
    id: 'gpt-5-mini',
    type: 'chat',
  },
  {
    description: 'GPT-5 超级轻量版本',
    displayName: 'gpt-5-nano',
    enabled: true,
    id: 'gpt-5-nano',
    type: 'chat',
  },
  {
    description: 'GPT-5 标准版本',
    displayName: 'gpt-5',
    enabled: true,
    id: 'gpt-5',
    type: 'chat',
  },
  {
    description: 'GPT-4.1 Mini 版本，升级版本',
    displayName: 'gpt-4.1-mini',
    enabled: true,
    id: 'gpt-4.1-mini',
    type: 'chat',
  },
  {
    description: 'GPT-4.1 超级轻量版本',
    displayName: 'gpt-4.1-nano',
    enabled: true,
    id: 'gpt-4.1-nano',
    type: 'chat',
  },
  {
    description: 'GPT-4.1 标准版本',
    displayName: 'gpt-4.1',
    enabled: true,
    id: 'gpt-4.1',
    type: 'chat',
  },
  {
    description: 'GPT-4o Mini 经济版本',
    displayName: 'gpt-4o-mini',
    enabled: true,
    id: 'gpt-4o-mini',
    type: 'chat',
  },
  {
    description: 'O4 Mini 版本',
    displayName: 'o4-mini-2025-04-16',
    enabled: true,
    id: 'o4-mini-2025-04-16',
    type: 'chat',
  },
  {
    description: 'O3 Pro 专业版本',
    displayName: 'o3-pro-2025-06-10',
    enabled: true,
    id: 'o3-pro-2025-06-10',
    type: 'chat',
  },
  {
    description: 'Claude Opus 4.1 最强版本',
    displayName: 'claude-opus-4-1',
    enabled: true,
    id: 'claude-opus-4-1-20250805',
    type: 'chat',
  },
  {
    description: 'Claude Opus 4.1 思考版本',
    displayName: 'claude-opus-4-1-20250805-thinking',
    enabled: true,
    id: 'claude-opus-4-1-20250805-thinking',
    type: 'chat',
  },
  {
    description: 'Claude Sonnet 4 版本',
    displayName: 'claude-sonnet-4-20250514',
    enabled: true,
    id: 'claude-sonnet-4-20250514',
    type: 'chat',
  },
  {
    description: 'Claude Sonnet 4 思考版本',
    displayName: 'claude-sonnet-4-20250514-thinking',
    enabled: true,
    id: 'claude-sonnet-4-20250514-thinking',
    type: 'chat',
  },
  {
    description: 'Claude 3.7 Sonnet 最新版本',
    displayName: 'claude-3-7-sonnet-latest',
    enabled: true,
    id: 'claude-3-7-sonnet-latest',
    type: 'chat',
  },
  {
    description: 'Claude 3.5 Haiku 最新版本',
    displayName: 'claude-3-5-haiku-latest',
    enabled: true,
    id: 'claude-3-5-haiku-latest',
    type: 'chat',
  },
  {
    description: 'Gemini 2.5 Pro 专业版本',
    displayName: 'gemini-2.5-pro',
    enabled: true,
    id: 'gemini-2.5-pro',
    type: 'chat',
  },
  {
    description: 'Gemini 2.5 Flash 快速版本',
    displayName: 'gemini-2.5-flash',
    enabled: true,
    id: 'gemini-2.5-flash',
    type: 'chat',
  },
  {
    description: 'Gemini 2.5 Flash Lite 轻量版本',
    displayName: 'gemini-2.5-flash-lite',
    enabled: true,
    id: 'gemini-2.5-flash-lite',
    type: 'chat',
  },
  {
    description: 'Gemini 2.0 Flash 最新版本',
    displayName: 'gemini-2.0-flash',
    enabled: true,
    id: 'gemini-2.0-flash',
    type: 'chat',
  },
  {
    description: 'Grok 4 最新版本',
    displayName: 'grok-4-0709',
    enabled: true,
    id: 'grok-4-0709',
    type: 'chat',
  },
  {
    description: 'Grok 3 版本',
    displayName: 'grok-3',
    enabled: true,
    id: 'grok-3',
    type: 'chat',
  },
  {
    description: 'Grok 3 Mini 版本',
    displayName: 'grok-3-mini',
    enabled: true,
    id: 'grok-3-mini',
    type: 'chat',
  },
  {
    description: 'Grok 2 图像版本',
    displayName: 'grok-2-image-1212',
    enabled: true,
    id: 'grok-2-image-1212',
    type: 'chat',
  },
  {
    description: 'DeepSeek v3.1 最新版本',
    displayName: 'deepseek-v3.1',
    enabled: true,
    id: 'deepseek-v3.1',
    type: 'chat',
  },
  {
    description: 'DeepSeek v3 版本',
    displayName: 'deepseek-v3',
    enabled: true,
    id: 'deepseek-v3',
    type: 'chat',
  },
  {
    description: 'DeepSeek R1 推理版本',
    displayName: 'deepseek-r1-0528',
    enabled: true,
    id: 'deepseek-r1-0528',
    type: 'chat',
  },
  {
    description: 'DeepSeek Chat 聊天版本',
    displayName: 'deepseek-chat',
    enabled: true,
    id: 'deepseek-chat',
    type: 'chat',
  },
  {
    description: 'DeepSeek Reasoner 推理专家',
    displayName: 'deepseek-reasoner',
    enabled: true,
    id: 'deepseek-reasoner',
    type: 'chat',
  },
];

export default cometapiChatModels;
