// Generated by tools/sync_integration_catalogs.py from the public
// EmpirioLabs /v1/models catalog. Do not hand-edit: re-run the generator.
import type { ModelParamsSchema } from '../standard-parameters';
import type { AIChatModelCard, AIImageModelCard, AIVideoModelCard } from '../types/aiModel';

// https://empiriolabs.ai/models
const empiriolabsChatModels: AIChatModelCard[] = [
  {
    abilities: {
      reasoning: true,
    },
    description:
      'Pairs DeepSeek R1 chain-of-thought reasoning with Anthropic Claude creative and code generation behind a unified, data-controlled interface.',
    displayName: 'DeepReasoning',
    id: 'deepreasoning',
    maxOutput: 32_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 128_000,
    description:
      'Open-source Mixture-of-Experts LLM tuned for high-efficiency reasoning, coding, and general language tasks across long-form prompts.',
    displayName: 'DeepSeek V3.2',
    id: 'deepseek-v3-2',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.57, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.71, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Lightweight MoE model with 284B total / 13B active parameters and native 1M context, tuned for low-latency, cost-effective high-concurrency use.',
    displayName: 'DeepSeek V4 Flash',
    id: 'deepseek-v4-flash',
    maxOutput: 393_216,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.28, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Post-trained 0731 release with major gains across coding, repository work, tool use, and full-stack tasks, plus a 1M context window.',
    displayName: 'DeepSeek V4 Flash 0731',
    id: 'deepseek-v4-flash-0731',
    maxOutput: 393_216,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.14, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.28, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Flagship MoE LLM with 1.6T total / 49B active parameters and native 1M context for advanced math, logical inference, and specialized coding.',
    displayName: 'DeepSeek V4 Pro',
    id: 'deepseek-v4-pro',
    maxOutput: 393_216,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.65, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.3, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Original multi-agent conductor for hard reasoning, coding, and research, with 1M context, image input, function calling, and web search.',
    displayName: 'Fugu Ultra v1.0',
    id: 'fugu-ultra-v1-0',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 7.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 45, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Updated multi-agent conductor for hard reasoning, coding, and research, with distinct max effort, 1M context, image input, and web search.',
    displayName: 'Fugu Ultra v1.1',
    id: 'fugu-ultra-v1-1',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 30, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      vision: true,
    },
    contextWindowTokens: 128_000,
    description:
      'Open-source vision-language model with 128K context, 140+ languages, improved math/reasoning, structured outputs, and function calling.',
    displayName: 'Gemma 3 27B',
    id: 'gemma-3-27b',
    maxOutput: 8_192,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    description:
      'Gemma 4 26B A4B is a Google open multimodal model with 256K context, text, image, and video input, tools, and structured output.',
    displayName: 'Gemma 4 26B-A4B',
    id: 'gemma-4-26b-a4b',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.05, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.29, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 200_000,
    description:
      'Free lightweight GLM-4.5 text model for reasoning, coding, long-form chat, and general language tasks.',
    displayName: 'GLM 4.5 Flash',
    id: 'glm-4-5-flash',
    maxOutput: 98_304,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 128_000,
    description:
      'Free multimodal GLM-4.6V model for image, video, file, and text understanding with native function calling.',
    displayName: 'GLM 4.6V Flash',
    id: 'glm-4-6v-flash',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 200_000,
    description:
      'Free lightweight GLM-4.7 text model for coding, reasoning, long-context writing, and general chat.',
    displayName: 'GLM 4.7 Flash',
    id: 'glm-4-7-flash',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 202_000,
    description:
      'Long-context Zhipu AI reasoning model with 202K context, 128K output, tool calling, structured output, and cache support.',
    displayName: 'GLM 5.1',
    id: 'glm-5-1',
    pricing: {
      units: [
        { name: 'textInput', rate: 0.825, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.301, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Reasoning and coding model with a 1M token context, 128K output, adjustable reasoning effort, native web search, and tool calling.',
    displayName: 'GLM 5.2',
    id: 'glm-5-2',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.4, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Kimi K2.6 is a Moonshot multimodal reasoning model with 256K context, strong coding, and text, image, and video inputs.',
    displayName: 'Kimi K2.6',
    id: 'kimi-k2-6',
    maxOutput: 16_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.8939, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.7131, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      "Kimi K2.7 Code is Moonshot's trillion-parameter agentic coding model with 256K context, always-on reasoning, and text, image, and video inputs.",
    displayName: 'Kimi K2.7 Code',
    id: 'kimi-k2-7-code',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.95, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      "Kimi K2.7 Code Highspeed is the faster-serving tier of Moonshot's agentic coding model, with 256K context, always-on reasoning, and image and video input.",
    displayName: 'Kimi K2.7 Code Highspeed',
    id: 'kimi-k2-7-code-highspeed',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.9, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      "Kimi K3 is Moonshot's flagship reasoning model with a 1M token context, always-on thinking, native web search, and text, image, and video inputs.",
    displayName: 'Kimi K3',
    id: 'kimi-k3',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Multimodal model with native visual and audio understanding on a 1M context, designed to reason and act across modalities in agentic workflows.',
    displayName: 'MiMo V2.5',
    id: 'mimo-v2-5',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.7, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.4, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Top-tier model for agentic workflows, complex software engineering, and long-horizon tasks, sustaining work across 1000+ tool calls on 1M context.',
    displayName: 'MiMo V2.5 Pro',
    id: 'mimo-v2-5-pro',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 2.175, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.35, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 200_000,
    description:
      'MiniMax M2.7 is a general-purpose reasoning chat model with interleaved thinking, function calling, and prompt caching.',
    displayName: 'MiniMax M2.7',
    id: 'minimax-m2-7',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 200_000,
    description:
      'High-speed M2.7 variant tuned for fast inference with strong general-purpose performance with strong agentic capabilities.',
    displayName: 'MiniMax M2.7 Highspeed',
    id: 'minimax-m2-7-highspeed',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.2, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'MiniMax M3 is a multimodal reasoning model for coding, agents, and long-context analysis with text, image, and video input.',
    displayName: 'MiniMax M3',
    id: 'minimax-m3',
    maxOutput: 524_288,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.225, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.9, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 130_000,
    description:
      'Cost-efficient language model offering strong reasoning and multimodal performance for general production workloads at competitive latency.',
    displayName: 'Mistral Medium 3',
    id: 'mistral-medium-3',
    maxOutput: 40_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 131_000,
    description:
      'Enterprise-grade model with strong reasoning, coding, and STEM performance, supporting hybrid, on-prem, and in-VPC deployments.',
    displayName: 'Mistral Medium 3.1',
    id: 'mistral-medium-3-1',
    maxOutput: 40_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.52, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 128_000,
    description:
      '24B-parameter multimodal model with 128K context for image analysis, programming, math, and multilingual tasks, tuned for efficient local inference.',
    displayName: 'Mistral Small 3.1',
    id: 'mistral-small-3-1',
    maxOutput: 32_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Hybrid model unifying Instruct, Reasoning (Magistral), and Devstral families: 40% lower completion time and 3x throughput vs Small 3.',
    displayName: 'Mistral Small 4',
    id: 'mistral-small-4',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.15, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_048_576,
    description:
      'Meta frontier reasoning model with a 1,048,576-token context plus image, video, audio, and PDF understanding, web search, and tool calling.',
    displayName: 'Muse Spark 1.1',
    id: 'muse-spark-1-1',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_048_576,
    description:
      "Meta's updated frontier reasoning model with a 1,048,576-token context, image, video, audio, and PDF understanding, web search, and tool calling.",
    displayName: 'Muse Spark 1.2',
    id: 'muse-spark-1-2',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.25, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 300_000,
    description:
      'Low-cost multimodal foundation model for text, images, and video on a 300K context (up to ~30 min video), tuned for speed and affordability.',
    displayName: 'Nova Lite 1.0',
    id: 'nova-lite-1-0',
    maxOutput: 5_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.069, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.28, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Fast, cost-effective multimodal reasoning model for text, images, documents, and video on a 1M context (long docs and ~90 min clips).',
    displayName: 'Nova Lite 2',
    id: 'nova-lite-2',
    maxOutput: 32_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.38, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.16, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
    },
    contextWindowTokens: 128_000,
    description:
      'Text-only foundation model tuned for ultra-low latency and cost on 128K context. Strong for summarization, translation, and chat with 44% cache discount.',
    displayName: 'Nova Micro 1.0',
    id: 'nova-micro-1-0',
    maxOutput: 5_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.04, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.16, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Most capable model in the family. Multimodal text/image/video on a 1M context with chain-of-thought reasoning across tools and data sources.',
    displayName: 'Nova Premier 1.0',
    id: 'nova-premier-1-0',
    maxOutput: 32_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 15, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 300_000,
    description:
      'Multimodal foundation model balancing accuracy, speed, and cost for text, images, and video on 300K context (up to ~30 min video).',
    displayName: 'Nova Pro 1.0',
    id: 'nova-pro-1-0',
    maxOutput: 5_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 2.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 9.6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Qwen3.5 122B-A10B is a multimodal reasoning model with 256K context, efficient sparse MoE inference, and text, image, and video input.',
    displayName: 'Qwen3.5 122B-A10B',
    id: 'qwen3-5-122b-a10b',
    maxOutput: 64_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.115, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.917, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Qwen3.5 27B is a dense multimodal reasoning model with fast responses, 256K context, and text, image, and video understanding.',
    displayName: 'Qwen3.5 27B',
    id: 'qwen3-5-27b',
    maxOutput: 64_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.086, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.688, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Qwen3.5 35B-A3B is an efficient native vision-language model with sparse MoE routing, deep thinking, and text, image, and video input.',
    displayName: 'Qwen3.5 35B-A3B',
    id: 'qwen3-5-35b-a3b',
    maxOutput: 64_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.057, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.459, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Qwen3.5 397B-A17B is a flagship multimodal reasoning model for language, code, agents, GUI tasks, and image and video understanding.',
    displayName: 'Qwen3.5 397B-A17B',
    id: 'qwen3-5-397b-a17b',
    maxOutput: 64_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.172, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.032, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    description:
      'Qwen3.5 4B is a low-cost multimodal reasoning model with 256K context, image and video input, function tools, and structured output.',
    displayName: 'Qwen3.5 4B',
    id: 'qwen3-5-4b',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.04, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.07, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 262_144,
    description:
      'Qwen3.5 9B is a compact multimodal reasoning model with 256K context, image and video input, function tools, and structured output.',
    displayName: 'Qwen3.5 9B',
    id: 'qwen3-5-9b',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.09, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.13, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Vision-language model with hybrid linear-attention plus sparse MoE, 1M context, and fast multimodal text/image/video inference.',
    displayName: 'Qwen3.5 Flash',
    id: 'qwen3-5-flash',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.09, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.368, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Cost-efficient omni-modal model handling text, image, audio, and video, with up to 3 hours of audio and 1 hour of video across 90+ languages.',
    displayName: 'Qwen3.5 Omni Flash',
    id: 'qwen3-5-omni-flash',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.2, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Flagship omni-modal model for text, image, audio, and video. 3h audio, 1h video, 90+ input and 30+ output languages, 55 voice timbres.',
    displayName: 'Qwen3.5 Omni Plus',
    id: 'qwen3-5-omni-plus',
    maxOutput: 32_768,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 8.3, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Multimodal model with hybrid architecture for efficient deep thinking and visual understanding across text, image, and video on a 1M context.',
    displayName: 'Qwen3.5 Plus',
    id: 'qwen3-5-plus',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.36, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.21, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Qwen3.6 27B improves agentic coding, STEM reasoning, spatial vision, OCR, and text, image, and video understanding on 256K context.',
    displayName: 'Qwen3.6 27B',
    id: 'qwen3-6-27b',
    maxOutput: 64_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.412564, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.475384, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 131_072,
    description:
      'Qwen3.6 35B A3B is a 256-expert mixture-of-experts reasoning model with 128K context, function tools, and strict structured JSON output.',
    displayName: 'Qwen3.6 35B A3B',
    id: 'qwen3-6-35b-a3b',
    maxOutput: 16_384,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.07, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.42, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Fast Qwen3.6 vision-language model for agentic coding, math reasoning, spatial understanding, OCR, and text, image, and video input.',
    displayName: 'Qwen3.6 Flash',
    id: 'qwen3-6-flash',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.25, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Largest preview variant in the 3.6 series (text-only): improved coding agent execution, stronger front-end skills, and broader long-tail knowledge.',
    displayName: 'Qwen3.6 Max Preview',
    id: 'qwen3-6-max-preview',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.31, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 7.88, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Vision-language model with major upgrades over 3.5: agentic and front-end coding, multimodal recognition, OCR, and object localization.',
    displayName: 'Qwen3.6 Plus',
    id: 'qwen3-6-plus',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Fast Qwen3.7 vision-language model for text, image, video, tool use, and agentic tasks, with implicit caching and a 1M token context.',
    displayName: 'Qwen3.7 Flash',
    id: 'qwen3-7-flash',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.03, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.13, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Qwen3.7 Max is a flagship text model for coding, productivity, long-running agents, deep thinking, tools, and 1M-token context.',
    displayName: 'Qwen3.7 Max',
    id: 'qwen3-7-max',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 2.5, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 7.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Cost-effective Qwen3.7 vision-language model for text, image, video, coding, tool use, GUI understanding, and 1M-context workflows.',
    displayName: 'Qwen3.7 Plus',
    id: 'qwen3-7-plus',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 1_000_000,
    description:
      'Trillion-scale MoE flagship for coding, long-horizon agents, and professional work, with image and video understanding across a 1M-token context.',
    displayName: 'Qwen3.8 Max',
    id: 'qwen3-8-max',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 6, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description:
      '256K-context flagship with major improvements in reasoning, instruction following, and multilingual support, plus higher coding/math accuracy.',
    displayName: 'Qwen3 Max',
    id: 'qwen3-max',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.08, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 5.52, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Preview release with major gains over the 2.5 series in Chinese-English understanding, complex instructions, multilingual ability, and tool use.',
    displayName: 'Qwen3 Max Preview',
    id: 'qwen3-max-preview',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.08, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 4.8, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Reasoning model with adaptive tool use (search, memory, code interpreter) and test-time scaling for higher accuracy on complex tasks.',
    displayName: 'Qwen3 Max Thinking',
    id: 'qwen3-max-thinking',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.08, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 5.52, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Coding-tuned 256K-context model with strong front-end results and multilingual programming support for AI coding tools and agents.',
    displayName: 'Seed 2.0 Code',
    id: 'seed-2-0-code',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.4, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.4, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Balanced general-purpose model for high-frequency enterprise workloads: information processing, content, search, and data analysis.',
    displayName: 'Seed 2.0 Lite',
    id: 'seed-2-0-lite',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.31, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 2.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Latency-focused multimodal model with 256K context, four reasoning effort modes, and image/video understanding for high-concurrency use.',
    displayName: 'Seed 2.0 Mini',
    id: 'seed-2-0-mini',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.12, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.5, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Flagship general model with 256K context for complex reasoning, multimodal understanding, structured generation, and tool-augmented execution.',
    displayName: 'Seed 2.0 Pro',
    id: 'seed-2-0-pro',
    maxOutput: 128_000,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.63, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.79, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'Next-generation coding and agent model with engineering-grade code delivery, long-horizon autonomy, and 256K multimodal understanding.',
    displayName: 'Seed 2.1 Turbo',
    id: 'seed-2-1-turbo',
    maxOutput: 65_536,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.63, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.13, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description:
      'StepFun text reasoning model for agents, coding, tool calling, and long-context analysis.',
    displayName: 'Step 3.5 Flash',
    id: 'step-3-5-flash',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.1, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
    },
    contextWindowTokens: 256_000,
    description: 'Agent-optimized Step 3.5 Flash variant with low and high reasoning effort modes.',
    displayName: 'Step 3.5 Flash 2603',
    id: 'step-3-5-flash-2603',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.1, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 0.3, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    abilities: {
      functionCall: true,
      reasoning: true,
      vision: true,
    },
    contextWindowTokens: 256_000,
    description:
      'StepFun multimodal reasoning model with image and video input, tool calling, adjustable reasoning effort, and 256K context.',
    displayName: 'Step 3.7 Flash',
    id: 'step-3-7-flash',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 0.2, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 1.15, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
  {
    contextWindowTokens: 256_000,
    description:
      'StepFun audio and text conversation model with text output and paralinguistic understanding.',
    displayName: 'StepAudio 2.5 Chat',
    id: 'stepaudio-2-5-chat',
    maxOutput: 131_072,
    pricing: {
      units: [
        { name: 'textInput', rate: 1.43, strategy: 'fixed', unit: 'millionTokens' },
        { name: 'textOutput', rate: 3.57, strategy: 'fixed', unit: 'millionTokens' },
      ],
    },
    type: 'chat',
  },
];

// Image-generation parameter schemas. EmpirioLabs serves these through the
// OpenAI-compatible /v1/images/generations endpoint, so the default image
// handler covers them with no custom runtime code. imageUrl maps to the
// upstream image-edit input, enabling image-to-image where the model supports it.
export const amazonNovaCanvasParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: '1:1',
    enum: [
      '1:1',
      '3:4',
      '2:3',
      '9:16',
      '1:2',
      '1:3',
      '1:4',
      '4:3',
      '3:2',
      '16:9',
      '2:1',
      '3:1',
      '4:1',
    ],
  },
  cfg: { default: 7.5, max: 20, min: 1, step: 0.5 },
  imageUrl: { default: null },
  prompt: { default: '' },
  quality: { default: 'standard', enum: ['standard', 'premium'] },
  seed: { default: null },
};

export const flux2Klein4bParamsSchema: ModelParamsSchema = {
  aspectRatio: { default: '1:1', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'] },
  cfg: { default: 1, max: 8, min: 0, step: 0.5 },
  prompt: { default: '' },
  seed: { default: null },
  steps: { default: 4, max: 12, min: 1 },
};

export const gptImage2ParamsSchema: ModelParamsSchema = {
  imageUrl: { default: null },
  prompt: { default: '' },
  quality: { default: 'medium', enum: ['low', 'medium', 'high'] },
  size: { default: '1024x1024', enum: ['1024x1024', '1536x1024', '1024x1536'] },
};

export const hunyuanImage3ParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: '1:1',
    enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '5:4', '4:5', '21:9', '9:21'],
  },
  prompt: { default: '' },
  seed: { default: null },
};

export const janusProDeepseekParamsSchema: ModelParamsSchema = {
  imageUrl: { default: null },
  prompt: { default: '' },
};

export const qwenImage20ParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: '16:9',
    enum: ['16:9', '9:16', '1:1', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5'],
  },
  imageUrl: { default: null },
  prompt: { default: '' },
  promptExtend: { default: true },
  seed: { default: null },
  watermark: { default: false },
};

export const qwenImage30ParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: 'auto',
    enum: ['auto', '1:1', '16:9', '9:16', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5'],
  },
  imageUrl: { default: null },
  prompt: { default: '' },
  promptExtend: { default: true },
  resolution: { default: '2K', enum: ['auto', '1K', '2K'] },
  seed: { default: null },
  watermark: { default: false },
};

export const seedream50LiteParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: 'auto',
    enum: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '21:9'],
  },
  imageUrl: { default: null },
  prompt: { default: '' },
  quality: { default: '2K', enum: ['2K', '3K'] },
  watermark: { default: false },
};

export const seedream50ProParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: 'auto',
    enum: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '21:9'],
  },
  imageUrl: { default: null },
  prompt: { default: '' },
  quality: { default: '2K', enum: ['1K', '1.5K', '2K'] },
  watermark: { default: false },
};

export const stepImageEdit2ParamsSchema: ModelParamsSchema = {
  cfg: { default: 1, max: 10, min: 1, step: 0.5 },
  imageUrl: { default: null },
  prompt: { default: '' },
  seed: { default: null },
  size: {
    default: '1024x1024',
    enum: ['1024x1024', '768x1360', '896x1184', '1360x768', '1184x896'],
  },
  steps: { default: 8, max: 50, min: 1 },
};

export const wan21ImageParamsSchema: ModelParamsSchema = {
  aspectRatio: { default: '1:1', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'] },
  prompt: { default: '' },
  promptExtend: { default: true },
  seed: { default: null },
  watermark: { default: false },
};

export const wan22ImageParamsSchema: ModelParamsSchema = {
  aspectRatio: { default: '1:1', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'] },
  prompt: { default: '' },
  promptExtend: { default: true },
  seed: { default: null },
  watermark: { default: false },
};

export const wan25ImageParamsSchema: ModelParamsSchema = {
  aspectRatio: { default: '1:1', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'] },
  imageUrl: { default: null },
  prompt: { default: '' },
  promptExtend: { default: true },
  seed: { default: null },
  watermark: { default: false },
};

export const wan27ImageParamsSchema: ModelParamsSchema = {
  aspectRatio: {
    default: '16:9',
    enum: ['16:9', '1:1', '9:16', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5'],
  },
  imageUrl: { default: null },
  prompt: { default: '' },
  resolution: { default: '2K', enum: ['1K', '2K', '4K'] },
  seed: { default: null },
  watermark: { default: false },
};

const empiriolabsImageModels: AIImageModelCard[] = [
  {
    description:
      'Image generation and editing model creating and modifying images from text or image inputs, with inpainting, virtual try-on, and style controls.',
    displayName: 'Amazon Nova Canvas',
    enabled: true,
    id: 'amazon-nova-canvas',
    organization: 'Amazon',
    parameters: amazonNovaCanvasParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.12, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Apache-licensed 4B FLUX.2 Klein image generation and editing model with text-to-image, reference-image editing, and creative workflow support.',
    displayName: 'FLUX.2 Klein 4B',
    enabled: true,
    id: 'flux-2-klein-4b',
    organization: 'Black Forest Labs',
    parameters: flux2Klein4bParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.0085, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      "OpenAI's flagship image model with strong prompt fidelity, crisp text rendering, and instruction-based editing across up to 16 reference images.",
    displayName: 'GPT Image 2',
    enabled: true,
    id: 'gpt-image-2',
    organization: 'OpenAI',
    parameters: gptImage2ParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.012, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Open-source text-to-image model on a multimodal Mixture-of-Experts architecture with photorealistic detail and strong multilingual text rendering.',
    displayName: 'Hunyuan Image 3',
    enabled: true,
    id: 'hunyuan-image-3',
    organization: 'Tencent',
    parameters: hunyuanImage3ParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.13, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Autoregressive framework on the Janus Pro 7B model that unifies multimodal understanding and image generation in one architecture.',
    displayName: 'Janus-Pro DeepSeek',
    enabled: true,
    id: 'janus-pro-deepseek',
    organization: 'DeepSeek',
    parameters: janusProDeepseekParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.03, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Unified image generation and editing model with class-leading complex Chinese/English text rendering, realistic textures, and multi-image fusion.',
    displayName: 'Qwen Image 2.0',
    enabled: true,
    id: 'qwen-image-2-0',
    organization: 'Alibaba',
    parameters: qwenImage20ParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.035, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Qwen image generation and editing with Base and Pro variants, multilingual typography, multi-image references, and controllable 1K or 2K output.',
    displayName: 'Qwen Image 3.0',
    enabled: true,
    id: 'qwen-image-3-0',
    organization: 'Alibaba',
    parameters: qwenImage30ParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.03, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Unified multimodal image model that reasons through prompts before rendering, producing high-resolution and consistent edits and brand visuals.',
    displayName: 'Seedream 5.0 Lite',
    enabled: true,
    id: 'seedream-5-0-lite',
    organization: 'ByteDance',
    parameters: seedream50LiteParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.035, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Premium Seedream image model for text-to-image, edits, and multi-reference fusion with 1K, 1.5K, and 2K output plus Standard or Fast prompt optimization.',
    displayName: 'Seedream 5.0 Pro',
    enabled: true,
    id: 'seedream-5-0-pro',
    organization: 'ByteDance',
    parameters: seedream50ProParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'StepFun image generation and image editing model for text-to-image and single-image edits.',
    displayName: 'Step Image Edit 2',
    enabled: true,
    id: 'step-image-edit-2',
    organization: 'stepfun',
    parameters: stepImageEdit2ParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.003, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      "Alibaba's Wan 2.1 text-to-image model with turbo and plus tiers and up to 1440x1440 output at low per-image pricing.",
    displayName: 'Wan2.1 Image',
    enabled: true,
    id: 'wan2-1-image',
    organization: 'Alibaba',
    parameters: wan21ImageParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.025, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      "Alibaba's Wan 2.2 text-to-image model with plus and flash tiers and up to 1440x1440 output at low per-image pricing.",
    displayName: 'Wan2.2 Image',
    enabled: true,
    id: 'wan2-2-image',
    organization: 'Alibaba',
    parameters: wan22ImageParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.05, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      "Alibaba's Wan 2.5 image model with text-to-image and multi-reference editing of up to 3 images at about 1.7 megapixels.",
    displayName: 'Wan2.5 Image',
    enabled: true,
    id: 'wan2-5-image',
    organization: 'Alibaba',
    parameters: wan25ImageParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.03, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
  {
    description:
      'Image generation and editing companion model: text-to-image, bounding-box edits, and cohesive image sets, with up to 4K output on Pro.',
    displayName: 'Wan2.7 Image',
    enabled: true,
    id: 'wan2-7-image',
    organization: 'Alibaba',
    parameters: wan27ImageParamsSchema,
    pricing: {
      units: [{ name: 'imageGeneration', rate: 0.03, strategy: 'fixed', unit: 'image' }],
    },
    type: 'image',
  },
];

// Video models are served through the async /v1/videos/generations endpoint
// (submit returns a job id, the result is polled at /v1/jobs/{id}). The
// EmpirioLabs runtime provider supplies createVideo + handlePollVideoStatus.
// Each card exposes only the parameters that map to a field the worker reads,
// and the runtime forwards them as the camelCase keys the provider translates.
const empiriolabsVideoModels: AIVideoModelCard[] = [
  {
    description:
      'Video generation model producing up to 2-minute multi-shot videos from text and optional image prompts with improved quality and consistency.',
    displayName: 'Amazon Nova Reel 1.1',
    enabled: true,
    id: 'amazon-nova-reel-1-1',
    organization: 'Amazon',
    parameters: {
      duration: { default: 6, max: 120, min: 6 },
      prompt: { default: '' },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.14, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Text-to-video, image-to-video, and reference-to-video generation with up to seven reference images for consistent characters, up to 15 seconds at 1080p.',
    displayName: 'Grok Imagine Video 1.5',
    enabled: true,
    id: 'grok-imagine-video-1-5',
    organization: 'xAI',
    parameters: {
      aspectRatio: { default: '1:1', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'] },
      duration: { default: 10, max: 15, min: 1 },
      imageUrl: { default: null },
      imageUrls: { default: [], maxCount: 4 },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['480p', '720p', '1080p'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.168, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Video model offering Text-to-Video, Image-to-Video, Reference-to-Video, and Video Edit modes with high-fidelity, motion-smooth output.',
    displayName: 'HappyHorse 1.0',
    enabled: true,
    id: 'happyhorse-1-0',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 15, min: 3 },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '1080p', enum: ['720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.24, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Text, image, and reference-to-video in one model. Cinematic motion, character consistency across up to 9 references, and synchronized native audio.',
    displayName: 'HappyHorse 1.1',
    enabled: true,
    id: 'happyhorse-1-1',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 15, min: 3 },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.14, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      '8.3B-parameter video model with native 720p output (upscalable to 1080p), strong motion coherence, and bilingual prompt understanding up to 10s.',
    displayName: 'Hunyuan Video 1.5',
    enabled: true,
    id: 'hunyuan-video-1-5',
    organization: 'Tencent',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 10, min: 1 },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '480p', enum: ['480p', '720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.061, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Text-to-video and image-to-video with synchronized native audio, at 720p or 1080p for 3 to 15 seconds, with aspect ratio and prompt control.',
    displayName: 'Kling 3.0 Turbo',
    enabled: true,
    id: 'kling-3-0-turbo',
    organization: 'Kuaishou',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1'] },
      duration: { default: 5, max: 15, min: 3 },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['720p', '1080p'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.18, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Video model in Standard or Pro modes with Text-to-Video, Image-to-Video, Reference-to-Video, editing, native sound, and multi-scene transitions.',
    displayName: 'Kling O3',
    enabled: true,
    id: 'kling-o3',
    organization: 'Kuaishou',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '1:1', '9:16'] },
      duration: { default: 5, max: 15, min: 3 },
      endImageUrl: { default: null },
      imageUrl: { default: null },
      imageUrls: { default: [], maxCount: 4 },
      prompt: { default: '' },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.168, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      "Kuaishou's Kling 3.0 video generator with text-to-video, first and last frame image-to-video, native audio, and 720p, 1080p, or 4K output.",
    displayName: 'Kling V3',
    enabled: true,
    id: 'kling-v3',
    organization: 'Kuaishou',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1'] },
      duration: { default: 5, max: 15, min: 3 },
      imageUrl: { default: null },
      prompt: { default: '' },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.168, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Generates 4 to 15 second clips at up to 2K with native stereo audio, following text, image, video, and audio references in one request.',
    displayName: 'MiniMax H3',
    enabled: true,
    id: 'minimax-h3',
    organization: 'MiniMax',
    parameters: {
      aspectRatio: {
        default: 'adaptive',
        enum: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      duration: { default: 6, max: 15, min: 4 },
      generateAudio: { default: false },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '768p', enum: ['768p', '2k'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.18, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Open-source 32B MoE foundation model that generates synchronized video and audio in one inference step with precise dual-tower lip-sync.',
    displayName: 'MOSS Video and Audio',
    enabled: true,
    id: 'moss-video-and-audio',
    organization: 'OpenMOSS',
    parameters: {
      aspectRatio: { default: 'landscape', enum: ['landscape', 'portrait'] },
      duration: { default: 8, max: 8, min: 2 },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['360p', '720p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 2.82, strategy: 'fixed', unit: 'video' }],
    },
    type: 'video',
  },
  {
    description:
      'Cinematic video generation in Text-to-Video, Image-to-Video, and Transition modes with high detail, fluid motion, and lifelike animations.',
    displayName: 'Pixverse v5',
    enabled: true,
    id: 'pixverse-v5',
    organization: 'PixVerse',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '4:3', '1:1', '3:4', '9:16'] },
      duration: { default: 5, enum: [5, 8], max: 8, min: 5 },
      endImageUrl: { default: null },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['360p', '540p', '720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.6, strategy: 'fixed', unit: 'video' }],
    },
    type: 'video',
  },
  {
    description:
      'Generates videos from text or 1-2 frame image prompts up to 1080p, multiple aspect ratios, 5-10s durations, with optional synchronized audio.',
    displayName: 'Pixverse v5.6',
    enabled: true,
    id: 'pixverse-v5-6',
    organization: 'PixVerse',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '4:3', '1:1', '3:4', '9:16'] },
      duration: { default: 5, enum: [5, 8, 10], max: 10, min: 5 },
      endImageUrl: { default: null },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '1080p', enum: ['360p', '540p', '720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.75, strategy: 'fixed', unit: 'video' }],
    },
    type: 'video',
  },
  {
    description:
      'Speed-optimized 2.0 video variant for cinematic clips with native audio sync, camera control, and stable motion at lower cost per render.',
    displayName: 'Seedance 2.0 Fast',
    enabled: true,
    id: 'seedance-2-0-fast',
    organization: 'ByteDance',
    parameters: {
      aspectRatio: {
        default: 'adaptive',
        enum: ['adaptive', '16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
      },
      duration: { default: 5, max: 15, min: 4 },
      endImageUrl: { default: null },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['480p', '720p'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.26, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'The fastest, most affordable Seedance 2.0 tier for short cinematic clips with native audio, camera control, and image or video inputs at 480p and 720p.',
    displayName: 'Seedance 2.0 Mini',
    enabled: true,
    id: 'seedance-2-0-mini',
    organization: 'ByteDance',
    parameters: {
      aspectRatio: {
        default: 'adaptive',
        enum: ['adaptive', '16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
      },
      duration: { default: 5, max: 15, min: 4 },
      endImageUrl: { default: null },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['480p', '720p'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.15, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Multimodal video model for cinematic output from text, image, audio, or video inputs, with stable motion and consistent characters.',
    displayName: 'Seedance 2.0 Pro',
    enabled: true,
    id: 'seedance-2-0-pro',
    organization: 'ByteDance',
    parameters: {
      aspectRatio: {
        default: 'adaptive',
        enum: ['adaptive', '16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
      },
      duration: { default: 5, max: 15, min: 4 },
      endImageUrl: { default: null },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['480p', '720p', '1080p', '4k'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.3, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Long-form video model for coherent clips up to 30 seconds, with up to 50 reference images, videos, and audio clips, native audio, editing, and extension.',
    displayName: 'Seedance 2.5',
    enabled: true,
    id: 'seedance-2-5',
    organization: 'ByteDance',
    parameters: {
      aspectRatio: {
        default: 'adaptive',
        enum: ['adaptive', '16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
      },
      duration: { default: 5, max: 30, min: 4 },
      endImageUrl: { default: null },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      resolution: { default: '720p', enum: ['480p', '720p'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.462, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Stable Video Infinity 2.0 Pro on WAN 2.2: extends still images into theoretically infinite-length video while keeping consistent character IDs.',
    displayName: 'SVI 2.0 Pro',
    enabled: true,
    id: 'svi-2-0-pro',
    organization: 'VITA-EPFL',
    parameters: {
      duration: { default: 18, max: 121.5, min: 18 },
      prompt: { default: '' },
      size: { default: '832x480', enum: ['832x480', '480x832', '720x1280', '1280x720'] },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.057, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      "Alibaba's Wan 2.1 video model with turbo and plus tiers for text-to-video, image-to-video, and first and last frame clips at 480p or 720p.",
    displayName: 'Wan 2.1',
    enabled: true,
    id: 'wan-2-1',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 5, min: 3 },
      imageUrl: { default: null },
      prompt: { default: '' },
      promptExtend: { default: true },
      resolution: { default: '720p', enum: ['480p', '720p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.036, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      "Alibaba's Wan 2.2 video family with standard and flash tiers, first and last frame interpolation, and 480p to 1080p output at low cost.",
    displayName: 'Wan 2.2',
    enabled: true,
    id: 'wan-2-2',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      imageUrl: { default: null },
      prompt: { default: '' },
      promptExtend: { default: true },
      resolution: { default: '1080p', enum: ['480p', '720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.1, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      "Alibaba's Wan 2.5 video model with text-to-video and image-to-video, native audio, optional custom audio tracks, and 480p to 1080p output.",
    displayName: 'Wan 2.5',
    enabled: true,
    id: 'wan-2-5',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 10, min: 5 },
      imageUrl: { default: null },
      prompt: { default: '' },
      promptExtend: { default: true },
      resolution: { default: '1080p', enum: ['480p', '720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.15, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Multimodal video generation model for cinematic, multi-shot stories with native audio-visual sync (lip-sync, dialogue, music, SFX).',
    displayName: 'Wan 2.6',
    enabled: true,
    id: 'wan-2-6',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 15, min: 5 },
      generateAudio: { default: true },
      imageUrl: { default: null },
      prompt: { default: '' },
      promptExtend: { default: true },
      resolution: { default: '1080p', enum: ['720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.15, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
  {
    description:
      'Multimodal video model supporting T2V, I2V, video editing, and reference-to-video, with high-fidelity output from text, image, or video inputs.',
    displayName: 'Wan 2.7',
    enabled: true,
    id: 'wan-2-7',
    organization: 'Alibaba',
    parameters: {
      aspectRatio: { default: '16:9', enum: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      duration: { default: 5, max: 15, min: 2 },
      imageUrl: { default: null },
      prompt: { default: '' },
      promptExtend: { default: true },
      resolution: { default: '1080p', enum: ['720p', '1080p'] },
      seed: { default: null },
    },
    pricing: {
      units: [{ name: 'videoGeneration', rate: 0.15, strategy: 'fixed', unit: 'second' }],
    },
    type: 'video',
  },
];

export const empiriolabsChatModelList = empiriolabsChatModels;
export const empiriolabsImageModelList = empiriolabsImageModels;
export const empiriolabsVideoModelList = empiriolabsVideoModels;

export const allModels = [
  ...empiriolabsChatModels,
  ...empiriolabsImageModels,
  ...empiriolabsVideoModels,
];

export default allModels;
