name: Setup Node and pnpm
description: Setup Node.js and pnpm for workflows

inputs:
  node-version:
    description: Node.js version
    required: true
  package-manager-cache:
    description: Pass-through to actions/setup-node package-manager-cache
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        package-manager-cache: ${{ inputs.package-manager-cache }}


