import { ModelProviderCard } from '@/types/llm';

const AiHubMix: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 65_536,
      description: 'DeepSeek R1 推理模型，具有强大的推理能力',
      displayName: 'DeepSeek R1',
      enabled: true,
      functionCall: true,
      id: 'DeepSeek-R1',
      reasoning: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'Claude Opus 4 最新版本，具有卓越的推理和创作能力',
      displayName: 'Claude Opus 4',
      enabled: true,
      functionCall: true,
      id: 'claude-opus-4-20250514',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'Claude Sonnet 4 最新版本，平衡性能与效率',
      displayName: 'Claude Sonnet 4',
      enabled: true,
      functionCall: true,
      id: 'claude-sonnet-4-20250514',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash 预览版，快速高效的多模态模型',
      displayName: 'Gemini 2.5 Flash',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-flash-preview-05-20',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash 无思维链版本',
      displayName: 'Gemini 2.5 Flash (No Think)',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-flash-preview-05-20-nothink',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash 搜索增强版本',
      displayName: 'Gemini 2.5 Flash (Search)',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-flash-preview-05-20-search',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'OpenAI o3 推理模型，具有强大的推理能力',
      displayName: 'o3',
      enabled: true,
      functionCall: true,
      id: 'o3',
      reasoning: true,
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'OpenAI o4-mini 小型推理模型，高效且经济',
      displayName: 'o4-mini',
      enabled: true,
      functionCall: true,
      id: 'o4-mini',
      reasoning: true,
      vision: true,
    },
    {
      contextWindowTokens: 1_047_576,
      description: 'GPT-4.1 旗舰模型，适用于复杂任务',
      displayName: 'GPT-4.1',
      enabled: true,
      functionCall: true,
      id: 'gpt-4.1',
      vision: true,
    },
    {
      contextWindowTokens: 1_047_576,
      description: 'GPT-4.1 mini 平衡智能、速度和成本',
      displayName: 'GPT-4.1 mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4.1-mini',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash 预览版 (04-17)',
      displayName: 'Gemini 2.5 Flash (04-17)',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-flash-preview-04-17',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000,
      description: 'Gemini 2.5 Pro 预览版，长上下文支持',
      displayName: 'Gemini 2.5 Pro',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-pro-preview-05-06',
      vision: true,
    },
    {
      contextWindowTokens: 235_000,
      description: 'Qwen3 235B 大型语言模型',
      displayName: 'Qwen3 235B',
      enabled: true,
      functionCall: true,
      id: 'Qwen/Qwen3-235B-A22B',
    },
    {
      contextWindowTokens: 32_000,
      description: 'Qwen3 32B 中型语言模型',
      displayName: 'Qwen3 32B',
      enabled: true,
      functionCall: true,
      id: 'Qwen/Qwen3-32B',
    },
  ],
  checkModel: 'gpt-4.1-mini',
  description: 'AiHubMix 通过统一的 API 接口提供对多种 AI 模型的访问。',
  id: 'aihubmix',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://docs.aihubmix.com/cn/api/Model-List',
  name: 'AiHubMix',
  settings: {
    proxyUrl: {
      placeholder: 'https://aihubmix.com/v1',
    },
    sdkType: 'openai',
    showModelFetcher: true,
  },
  url: 'https://aihubmix.com?utm_source=lobehub',
};

export default AiHubMix;
