import { ModelProviderCard } from '@/types/llm';

// ref :https://siliconflow.cn/zh-cn/models
const SiliconCloud: ModelProviderCard = {
  chatModels: [
    {
      description: 'Qwen2 是全新的大型语言模型系列，旨在优化指令式任务的处理。',
      displayName: 'Qwen2 1.5B',
      id: 'Qwen/Qwen2-1.5B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Qwen2 是全新的大型语言模型系列，具有更强的理解和生成能力。',
      displayName: 'Qwen2 7B',
      enabled: true,
      id: 'Qwen/Qwen2-7B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Qwen2 是全新的系列，57B A14B 型号在指令任务中表现卓越。',
      displayName: 'Qwen2 57B A14B',
      id: 'Qwen/Qwen2-57B-A14B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Qwen2 是先进的通用语言模型，支持多种指令类型。',
      displayName: 'Qwen2 72B',
      enabled: true,
      id: 'Qwen/Qwen2-72B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Qwen2-Math 专注于数学领域的问题求解，为高难度题提供专业解答。',
      displayName: 'Qwen2 Math 72B',
      enabled: true,
      id: 'Qwen/Qwen2-Math-72B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Qwen1.5 通过结合高级预训练和微调提升对话表达能力。',
      displayName: 'Qwen1.5 7B',
      id: 'Qwen/Qwen1.5-7B-Chat',
      tokens: 32_768,
    },
    {
      description: 'Qwen1.5 通过大规模数据集训练，擅长复杂的语言任务。',
      displayName: 'Qwen1.5 14B',
      id: 'Qwen/Qwen1.5-14B-Chat',
      tokens: 32_768,
    },
    {
      description: 'Qwen1.5 具备多领域问答和文本生成的能力。',
      displayName: 'Qwen1.5 32B',
      id: 'Qwen/Qwen1.5-32B-Chat',
      tokens: 32_768,
    },
    {
      description: '作为Qwen2 的测试版，Qwen1.5 使用大规模数据实现了更精确的对话功能。',
      displayName: 'Qwen1.5 110B',
      id: 'Qwen/Qwen1.5-110B-Chat',
      tokens: 32_768,
    },
    {
      description: 'Yi-1.5 是Yi系列的进化版本，拥有高质量的预训练和丰富的微调数据。',
      displayName: 'Yi-1.5 6B',
      id: '01-ai/Yi-1.5-6B-Chat',
      tokens: 4096,
    },
    {
      description: 'Yi-1.5 9B 支持16K Tokens, 提供高效、流畅的语言生成能力。',
      displayName: 'Yi-1.5 9B',
      enabled: true,
      id: '01-ai/Yi-1.5-9B-Chat-16K',
      tokens: 16_384,
    },
    {
      description: 'Yi-1.5 34B, 以丰富的训练样本在行业应用中提供优越表现。',
      displayName: 'Yi-1.5 34B',
      enabled: true,
      id: '01-ai/Yi-1.5-34B-Chat-16K',
      tokens: 16_384,
    },
    {
      description: '作为双语会话语言模型, ChatGLM3能处理中英文转换任务。',
      displayName: 'GLM-3 6B',
      id: 'THUDM/chatglm3-6b',
      tokens: 32_768,
    },
    {
      description: 'GLM-4 9B 开放源码版本，为会话应用提供优化后的对话体验。',
      displayName: 'GLM-4 9B',
      enabled: true,
      id: 'THUDM/glm-4-9b-chat',
      tokens: 32_768,
    },
    {
      description: 'InternLM2.5 提供多场景下的智能对话解决方案。',
      displayName: 'Internlm 2.5 7B',
      enabled: true,
      id: 'internlm/internlm2_5-7b-chat',
      tokens: 32_768,
    },
    {
      description: '创新的开源模型InternLM2.5，通过大规模的参数提高了对话智能。',
      displayName: 'Internlm 2.5 20B',
      enabled: true,
      id: 'internlm/internlm2_5-20b-chat',
      tokens: 32_768,
    },
    {
      description: 'DeepSeek V2.5 集合了先前版本的优秀特征，增强了通用和编码能力。',
      displayName: 'DeepSeek V2.5',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-V2.5',
      tokens: 32_768,
    },
    {
      description: 'DeepSeek V2 具备67亿参数，支持英中文本处理。',
      displayName: 'DeepSeek V2 Chat',
      id: 'deepseek-ai/DeepSeek-V2-Chat',
      tokens: 32_768,
    },
    {
      description: 'DeepSeek Coder V2 为代码任务设计, 专注于高效的代码生成。',
      displayName: 'DeepSeek V2 Coder',
      id: 'deepseek-ai/DeepSeek-Coder-V2-Instruct',
      tokens: 32_768,
    },
    {
      description: 'DeepSeek 67B 是为高复杂性对话训练的先进模型。',
      displayName: 'DeepSeek LLM 67B',
      id: 'deepseek-ai/deepseek-llm-67b-chat',
      tokens: 32_768,
    },
    {
      description: 'Gemma 2 是Google轻量化的开源文本模型系列。',
      displayName: 'Gemma 2 9B',
      enabled: true,
      id: 'google/gemma-2-9b-it',
      tokens: 8192,
    },
    {
      description: 'Gemma 2 延续了轻量化与高效的设计理念。',
      displayName: 'Gemma 2 27B',
      enabled: true,
      id: 'google/gemma-2-27b-it',
      tokens: 8192,
    },
    {
      description: 'LLaMA 3.1 提供多语言支持，是业界领先的生成模型之一。',
      displayName: 'Llama 3.1 8B',
      enabled: true,
      id: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'LLaMA 3.1 70B 提供多语言的高效对话支持。',
      displayName: 'Llama 3.1 70B',
      enabled: true,
      id: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'LLaMA 3.1 405B 是预训练和指令调整的强大机型。',
      displayName: 'Llama 3.1 405B',
      enabled: true,
      id: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
      tokens: 32_768,
    },
    {
      description: 'Reflection Llama 3.1 通过Reflection-Tuning技术提升推理能力。',
      displayName: 'Reflection Llama 3.1 70B',
      id: 'mattshumer/Reflection-Llama-3.1-70B',
      tokens: 32_768,
    },
    {
      description: 'LLaMA 3 支持大容量文本生成和指令解析。',
      displayName: 'Llama 3 70B',
      id: 'meta-llama/Meta-Llama-3-70B-Instruct',
      tokens: 8192,
    },
    {
      description: 'Mistral 7B 是按需 fine-tuning的模型，为任务提供优化解答。',
      displayName: 'Mistral 7B',
      id: 'mistralai/Mistral-7B-Instruct-v0.2',
      tokens: 32_768,
    },
    {
      description: 'Mixtral 8x7B 是预训练的稀疏混合专家模型，用于通用性文本任务。',
      displayName: 'Mistral 8x7B',
      id: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
      tokens: 32_768,
    },
  ],
  checkModel: 'Qwen/Qwen2-1.5B-Instruct',
  description:
    'SiliconFlow 致力于加速 AGI，以惠及人类，通过易用与成本低的 GenAI 堆栈提升大规模 AI 效率。',
  id: 'siliconcloud',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://siliconflow.cn/zh-cn/models',
  name: 'SiliconCloud',
  proxyUrl: {
    placeholder: 'https://api.siliconflow.cn/v1',
  },
  url: 'https://siliconflow.cn',
};

export default SiliconCloud;
