import { ModelProviderCard } from '@/types/llm';

// ref https://api.together.xyz/models
const TogetherAI: ModelProviderCard = {
  chatModels: [
    {
      displayName: '01-ai Yi Chat (34B)',
      enabled: true,
      functionCall: false,
      id: 'zero-one-ai/Yi-34B-Chat',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Allen AI OLMo Instruct (7B)',
      enabled: true,
      functionCall: false,
      id: 'allenai/OLMo-7B-Instruct',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'Allen AI OLMo Twin-2T (7B)',
      enabled: true,
      functionCall: false,
      id: 'allenai/OLMo-7B-Twin-2T',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'Allen AI OLMo (7B)',
      enabled: true,
      functionCall: false,
      id: 'allenai/OLMo-7B',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'Austism Chronos Hermes (13B)',
      enabled: true,
      functionCall: false,
      id: 'Austism/chronos-hermes-13b',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'Dolphin 2.5 Mixtral 8x7b',
      enabled: true,
      functionCall: false,
      id: 'cognitivecomputations/dolphin-2.5-mixtral-8x7b',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'DBRX Instruct',
      enabled: true,
      functionCall: false,
      id: 'databricks/dbrx-instruct',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Deepseek Coder Instruct (33B)',
      enabled: true,
      functionCall: false,
      id: 'deepseek-ai/deepseek-coder-33b-instruct',
      tokens: 16384,
      vision: false,
    },
    {
      displayName: 'DeepSeek LLM Chat (67B)',
      enabled: true,
      functionCall: false,
      id: 'deepseek-ai/deepseek-llm-67b-chat',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Platypus2 Instruct (70B)',
      enabled: true,
      functionCall: false,
      id: 'garage-bAInd/Platypus2-70B-instruct',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Google Gemma Instruct (2B)',
      enabled: true,
      functionCall: false,
      id: 'google/gemma-2b-it',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'Google Gemma Instruct (7B)',
      enabled: true,
      functionCall: false,
      id: 'google/gemma-7b-it',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'MythoMax-L2 (13B)',
      enabled: true,
      functionCall: false,
      id: 'Gryphe/MythoMax-L2-13b',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Vicuna v1.5 (13B)',
      enabled: true,
      functionCall: false,
      id: 'lmsys/vicuna-13b-v1.5',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Vicuna v1.5 (7B)',
      enabled: true,
      functionCall: false,
      id: 'lmsys/vicuna-7b-v1.5',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Meta Code Llama Instruct (13B)',
      enabled: true,
      functionCall: false,
      id: 'codellama/CodeLlama-13b-Instruct-hf',
      tokens: 16384,
      vision: false,
    },
    {
      displayName: 'Meta Code Llama Instruct (34B)',
      enabled: true,
      functionCall: false,
      id: 'codellama/CodeLlama-34b-Instruct-hf',
      tokens: 16384,
      vision: false,
    },
    {
      displayName: 'Meta Code Llama Instruct (70B)',
      enabled: true,
      functionCall: false,
      id: 'codellama/CodeLlama-70b-Instruct-hf',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Meta Code Llama Instruct (7B)',
      enabled: true,
      functionCall: false,
      id: 'codellama/CodeLlama-7b-Instruct-hf',
      tokens: 16384,
      vision: false,
    },
    {
      displayName: 'Meta LLaMA-2 Chat (70B)',
      enabled: true,
      functionCall: false,
      id: 'meta-llama/Llama-2-70b-chat-hf',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Meta LLaMA-2 Chat (13B)',
      enabled: true,
      functionCall: false,
      id: 'meta-llama/Llama-2-13b-chat-hf',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Meta LLaMA-2 Chat (7B)',
      enabled: true,
      functionCall: false,
      id: 'meta-llama/Llama-2-7b-chat-hf',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'WizardLM-2 (8x22B)',
      enabled: true,
      functionCall: false,
      id: 'microsoft/WizardLM-2-8x22B',
      tokens: 65536,
      vision: false,
    },
    {
      displayName: 'Mistral (7B) Instruct',
      enabled: true,
      functionCall: false,
      id: 'mistralai/Mistral-7B-Instruct-v0.1',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'Mistral (7B) Instruct v0.2',
      enabled: true,
      functionCall: false,
      id: 'mistralai/Mistral-7B-Instruct-v0.2',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Mixtral-8x7B Instruct (46.7B)',
      enabled: true,
      functionCall: false,
      id: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Nous Capybara v1.9 (7B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Capybara-7B-V1p9',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'Nous Hermes 2 - Mistral DPO (7B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-2-Mistral-7B-DPO',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Nous Hermes 2 - Mixtral 8x7B-DPO (46.7B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Nous Hermes 2 - Mixtral 8x7B-SFT (46.7B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Nous Hermes LLaMA-2 (7B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-llama-2-7b',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Nous Hermes Llama-2 (13B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-Llama2-13b',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Nous Hermes-2 Yi (34B)',
      enabled: true,
      functionCall: false,
      id: 'NousResearch/Nous-Hermes-2-Yi-34B',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'OpenChat OpenChat 3.5 (7B)',
      enabled: true,
      functionCall: false,
      id: 'openchat/openchat-3.5-1210',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'OpenOrca Mistral (7B) 8K',
      enabled: true,
      functionCall: false,
      id: 'Open-Orca/Mistral-7B-OpenOrca',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (0.5B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-0.5B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (1.8B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-1.8B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (4B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-4B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (7B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-7B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (14B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-14B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (32B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-32B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Qwen 1.5 Chat (72B)',
      enabled: true,
      functionCall: false,
      id: 'Qwen/Qwen1.5-72B-Chat',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Snorkel Mistral PairRM DPO (7B)',
      enabled: true,
      functionCall: false,
      id: 'snorkelai/Snorkel-Mistral-PairRM-DPO',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'Alpaca (7B)',
      enabled: true,
      functionCall: false,
      id: 'togethercomputer/alpaca-7b',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'OpenHermes-2-Mistral (7B)',
      enabled: true,
      functionCall: false,
      id: 'teknium/OpenHermes-2-Mistral-7B',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'OpenHermes-2.5-Mistral (7B)',
      enabled: true,
      functionCall: false,
      id: 'teknium/OpenHermes-2p5-Mistral-7B',
      tokens: 8192,
      vision: false,
    },
    {
      displayName: 'LLaMA-2-7B-32K-Instruct (7B)',
      enabled: true,
      functionCall: false,
      id: 'togethercomputer/Llama-2-7B-32K-Instruct',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'RedPajama-INCITE Chat (3B)',
      enabled: true,
      functionCall: false,
      id: 'togethercomputer/RedPajama-INCITE-Chat-3B-v1',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'RedPajama-INCITE Chat (7B)',
      enabled: true,
      functionCall: false,
      id: 'togethercomputer/RedPajama-INCITE-7B-Chat',
      tokens: 2048,
      vision: false,
    },
    {
      displayName: 'StripedHyena Nous (7B)',
      enabled: true,
      functionCall: false,
      id: 'togethercomputer/StripedHyena-Nous-7B',
      tokens: 32768,
      vision: false,
    },
    {
      displayName: 'ReMM SLERP L2 (13B)',
      enabled: true,
      functionCall: false,
      id: 'Undi95/ReMM-SLERP-L2-13B',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Toppy M (7B)',
      enabled: true,
      functionCall: false,
      id: 'Undi95/Toppy-M-7B',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'WizardLM v1.2 (13B)',
      enabled: true,
      functionCall: false,
      id: 'WizardLM/WizardLM-13B-V1.2',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Upstage SOLAR Instruct v1 (11B)',
      enabled: true,
      functionCall: false,
      id: 'upstage/SOLAR-10.7B-Instruct-v1.0',
      tokens: 4096,
      vision: false,
    },
    {
      displayName: 'Openjourney v4',
      enabled: true,
      functionCall: false,
      id: 'prompthero/openjourney',
      tokens: 2048,
      vision: true,
    },
    {
      displayName: 'Stable Diffusion 1.5',
      enabled: true,
      functionCall: false,
      id: 'runwayml/stable-diffusion-v1-5',
      tokens: 2048,
      vision: true,
    },
    {
      displayName: 'Realistic Vision 3.0',
      enabled: true,
      functionCall: false,
      id: 'SG161222/Realistic_Vision_V3.0_VAE',
      tokens: 2048,
      vision: true,
    },
    {
      displayName: 'Stable Diffusion 2.1',
      enabled: true,
      functionCall: false,
      id: 'stabilityai/stable-diffusion-2-1',
      tokens: 2048,
      vision: true,
    },
    {
      displayName: 'Stable Diffusion XL 1.0',
      enabled: true,
      functionCall: false,
      id: 'stabilityai/stable-diffusion-xl-base-1.0',
      tokens: 2048,
      vision: true,
    },
    {
      displayName: 'Analog Diffusion',
      enabled: true,
      functionCall: false,
      id: 'wavymulder/Analog-Diffusion',
      tokens: 2048,
      vision: true,
    },
  ],
  id: 'togetherai',
};

export default TogetherAI;