import DOMPurify from 'dompurify';

/**
 * Sanitizes SVG content to prevent XSS attacks while preserving safe SVG elements and attributes
 * @param content - The SVG content to sanitize
 * @returns Sanitized SVG content safe for rendering
 */
export const sanitizeSVGContent = (content: string): string => {
  return DOMPurify.sanitize(content, {
    FORBID_ATTR: [
      'onblur',
      'onchange',
      'onclick',
      'onerror',
      'onfocus',
      'onkeydown',
      'onkeypress',
      'onkeyup',
      'onload',
      'onmousedown',
      'onmouseout',
      'onmouseover',
      'onmouseup',
      'onreset',
      'onselect',
      'onsubmit',
      'onunload',
    ],
    FORBID_TAGS: ['embed', 'link', 'object', 'script', 'style'],
    KEEP_CONTENT: false,
    USE_PROFILES: { svg: true, svgFilters: true },
  });
};

/**
 * Sanitizes HTML content to prevent XSS attacks while preserving safe HTML elements
 * @param content - The HTML content to sanitize
 * @returns Sanitized HTML content safe for rendering
 */
export const sanitizeHTMLContent = (content: string): string => {
  return DOMPurify.sanitize(content, {
    ALLOWED_ATTR: [
      'alt',
      'class',
      'dominant-baseline',
      'fill',
      'font-family',
      'font-size',
      'font-weight',
      'height',
      'href',
      'id',
      'rel',
      'src',
      'stroke',
      'stroke-width',
      'style',
      'target',
      'text-anchor',
      'title',
      'transform',
      'width',
      'xmlns',
    ],
    ALLOWED_TAGS: [
      'a',
      'b',
      'body',
      'br',
      'canvas',
      'circle',
      'div',
      'em',
      'ellipse',
      'g',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'head',
      'html',
      'i',
      'img',
      'li',
      'line',
      'ol',
      'p',
      'path',
      'polygon',
      'polyline',
      'rect',
      'span',
      'strong',
      'svg',
      'table',
      'tbody',
      'td',
      'text',
      'th',
      'thead',
      'title',
      'tr',
      'u',
      'ul',
    ],
    ALLOW_DATA_ATTR: false,
    FORBID_ATTR: [
      'javascript:',
      'onblur',
      'onchange',
      'onclick',
      'onerror',
      'onfocus',
      'onkeydown',
      'onkeypress',
      'onkeyup',
      'onload',
      'onmousedown',
      'onmouseout',
      'onmouseover',
      'onmouseup',
      'onreset',
      'onselect',
      'onsubmit',
      'onunload',
    ],
    FORBID_TAGS: ['base', 'embed', 'link', 'meta', 'object', 'script'],
    KEEP_CONTENT: true,
  });
};
