import { isAutoGeneratedImageModelId } from 'model-bank/standardParameters';

const IMAGE_MODEL_SUFFIX = ':image';

interface ModelWithId {
  id: string;
}

interface DeduplicateRemoteModelsResult<T> {
  duplicateIds: string[];
  models: T[];
  removedCount: number;
}

export const deduplicateRemoteModels = <T extends ModelWithId>(
  models: T[],
): DeduplicateRemoteModelsResult<T> => {
  const duplicateIds: string[] = [];
  const duplicateIdSet = new Set<string>();
  const sourceModelIds = new Set(models.map(({ id }) => id));
  const modelMap = new Map<string, T>();

  for (const model of models) {
    if (!modelMap.has(model.id)) {
      modelMap.set(model.id, model);
      continue;
    }

    if (!duplicateIdSet.has(model.id)) {
      duplicateIds.push(model.id);
      duplicateIdSet.add(model.id);
    }

    const shouldKeepLast =
      isAutoGeneratedImageModelId(model.id) &&
      sourceModelIds.has(model.id.slice(0, -IMAGE_MODEL_SUFFIX.length));

    if (shouldKeepLast) {
      modelMap.delete(model.id);
      modelMap.set(model.id, model);
    }
  }

  return {
    duplicateIds,
    models: [...modelMap.values()],
    removedCount: models.length - modelMap.size,
  };
};
