packages:
  - '../../packages/electron-server-ipc'
  - '../../packages/electron-client-ipc'
  - '../../packages/file-loaders'
  - '../../packages/desktop-bridge'
  - '../../packages/types'
  - '../../packages/web-crawler'
  - '../../packages/ssrf-safe-fetch'
  - '.'
