import type { FtsSearchDocumentSourceMap } from '../schema';

const createdAt = '2026-01-01T00:00:00.000Z';
const updatedAt = '2026-01-02T00:00:00.000Z';
const capturedAt = '2026-01-03T00:00:00.000Z';

export const FTS_SEARCH_DOCUMENT_FIXTURES = {
  agents: {
    created_at: createdAt,
    description: 'Agent description',
    id: 'agent-1',
    slug: 'agent-slug',
    system_role: 'Agent system role',
    tags: ['coding', 'search'],
    title: 'Agent title',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    virtual: false,
    visibility: 'public',
    workspace_id: null,
  },
  chatGroups: {
    content: 'Group content',
    created_at: createdAt,
    description: 'Group description',
    group_id: null,
    id: 'chat-group-1',
    title: 'Group title',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    visibility: 'private',
    workspace_id: null,
  },
  documents: {
    content: 'Document content',
    created_at: createdAt,
    description: 'Document description',
    file_id: 'file-1',
    file_type: 'text/plain',
    id: 'document-1',
    knowledge_base_id: 'knowledge-base-inline',
    knowledge_base_ids: ['knowledge-base-file', 'knowledge-base-inline'],
    parent_id: null,
    slug: 'document-slug',
    source_type: 'file',
    title: 'Document title',
    total_char_count: 16,
    updated_at: updatedAt,
    user_id: 'search-document-user',
    visibility: 'public',
    workspace_id: null,
  },
  files: {
    created_at: createdAt,
    file_type: 'text/plain',
    id: 'file-1',
    knowledge_base_ids: ['knowledge-base-file'],
    name: 'fixture.txt',
    size: 128,
    source: null,
    updated_at: updatedAt,
    user_id: 'search-document-user',
    visibility: 'public',
    workspace_id: null,
  },
  knowledgeBases: {
    created_at: createdAt,
    description: 'Knowledge base description',
    id: 'knowledge-base-file',
    is_public: true,
    name: 'Knowledge base',
    type: 'file',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    visibility: 'private',
    workspace_id: null,
  },
  memoryActivities: {
    captured_at: capturedAt,
    created_at: createdAt,
    ends_at: null,
    feedback: 'Activity feedback',
    id: 'memory-activity-1',
    narrative: 'Activity narrative',
    notes: 'Activity notes',
    parent_details: 'Parent details',
    parent_memory_categories: ['work'],
    parent_summary: 'Parent summary',
    parent_tags: ['parent'],
    parent_title: 'Parent title',
    starts_at: capturedAt,
    status: 'pending',
    tags: ['activity'],
    type: 'task',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    user_memory_id: 'memory-1',
  },
  memoryContexts: {
    captured_at: capturedAt,
    created_at: createdAt,
    current_status: 'Context status',
    description: 'Context description',
    id: 'memory-context-1',
    parent_memory_categories: ['work'],
    parent_tags: ['parent'],
    parent_text: ['Parent title Parent summary Parent details'],
    tags: ['context'],
    title: 'Context title',
    type: 'project',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    user_memory_ids: ['memory-1'],
  },
  memoryExperiences: {
    action: 'Experience action',
    captured_at: capturedAt,
    created_at: createdAt,
    id: 'memory-experience-1',
    key_learning: 'Experience learning',
    parent_details: 'Parent details',
    parent_memory_categories: ['work'],
    parent_summary: 'Parent summary',
    parent_tags: ['parent'],
    parent_title: 'Parent title',
    possible_outcome: 'Experience outcome',
    reasoning: 'Experience reasoning',
    situation: 'Experience situation',
    tags: ['experience'],
    type: 'decision',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    user_memory_id: 'memory-1',
  },
  memoryIdentities: {
    captured_at: capturedAt,
    created_at: createdAt,
    description: 'Identity description',
    episodic_date: capturedAt,
    id: 'memory-identity-1',
    parent_details: 'Parent details',
    parent_memory_categories: ['work'],
    parent_summary: 'Parent summary',
    parent_tags: ['parent'],
    parent_title: 'Parent title',
    relationship: 'colleague',
    role: 'Engineer',
    tags: ['identity'],
    type: 'person',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    user_memory_id: 'memory-1',
  },
  memoryPreferences: {
    captured_at: capturedAt,
    conclusion_directives: 'Preference directives',
    created_at: createdAt,
    id: 'memory-preference-1',
    parent_details: 'Parent details',
    parent_memory_categories: ['work'],
    parent_summary: 'Parent summary',
    parent_tags: ['parent'],
    parent_title: 'Parent title',
    suggestions: 'Preference suggestions',
    tags: ['preference'],
    type: 'communication',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    user_memory_id: 'memory-1',
  },
  messages: {
    agent_id: 'agent-1',
    content: 'Message content',
    created_at: createdAt,
    group_id: 'chat-group-1',
    id: 'message-1',
    role: 'user',
    session_id: null,
    summary: 'Message summary',
    thread_id: null,
    topic_id: 'topic-1',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    workspace_id: null,
  },
  personaDocuments: {
    captured_at: capturedAt,
    created_at: createdAt,
    id: 'persona-document-1',
    persona: 'Persona body',
    profile: 'default',
    tagline: 'Persona tagline',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    version: 2,
  },
  topics: {
    agent_id: 'agent-1',
    content: 'Topic content',
    created_at: createdAt,
    description: 'Topic description',
    group_id: 'chat-group-1',
    id: 'topic-1',
    session_id: null,
    status: 'active',
    title: 'Topic title',
    updated_at: updatedAt,
    user_id: 'search-document-user',
    workspace_id: null,
  },
  userMemories: {
    captured_at: capturedAt,
    created_at: createdAt,
    details: 'Parent details',
    id: 'memory-1',
    memory_category: 'work',
    memory_layer: 'episodic',
    status: 'active',
    summary: 'Parent summary',
    tags: ['parent'],
    title: 'Parent title',
    updated_at: updatedAt,
    user_id: 'search-document-user',
  },
} as const satisfies FtsSearchDocumentSourceMap;
