export default {
  apikey: {
    display: {
      autoGenerated: '自动生成',
      copy: '复制',
      copyError: '复制失败',
      copySuccess: 'API Key 已复制到剪贴板',
      enterPlaceholder: '请输入',
      hide: '隐藏',
      neverExpires: '永不过期',
      neverUsed: '从未使用',
      show: '显示',
    },
    form: {
      fields: {
        expiresAt: {
          label: '过期时间',
          placeholder: '永不过期',
        },
        name: {
          label: '名称',
          placeholder: '请输入 API Key 名称',
        },
      },
      submit: '创建',
      title: '创建 API Key',
    },
    list: {
      actions: {
        create: '创建 API Key',
        delete: '删除',
        deleteConfirm: {
          actions: {
            cancel: '取消',
            ok: '确认',
          },
          content: '确认删除该 API Key 吗？',
          title: '确认操作',
        },
      },
      columns: {
        actions: '操作',
        expiresAt: '过期时间',
        key: '密钥',
        lastUsedAt: '最后使用时间',
        name: '名称',
        status: '启用状态',
      },
      title: 'API Key 列表',
    },
    validation: {
      required: '内容不得为空',
    },
  },
  date: {
    prevMonth: '上个月',
    recent30Days: '最近30天',
  },
  header: {
    desc: '管理您的账户信息。',
    title: '账户',
  },
  heatmaps: {
    legend: {
      less: '不活跃',
      more: '活跃',
    },
    months: {
      apr: '四月',
      aug: '八月',
      dec: '十二月',
      feb: '二月',
      jan: '一月',
      jul: '七月',
      jun: '六月',
      mar: '三月',
      may: '五月',
      nov: '十一月',
      oct: '十月',
      sep: '九月',
    },
    tooltip: '{{date}} 当日发送 {{count}} 条消息',
    totalCount: '过去一年共发送 {{count}} 条消息',
  },
  login: '登录',
  loginOrSignup: '登录 / 注册',
  profile: {
    avatar: '头像',
    email: '电子邮件地址',
    sso: {
      loading: '正在加载已绑定的第三方账户',
      providers: '连接的帐户',
      unlink: {
        description:
          '解绑后，您将无法使用 {{provider}} 账户“{{providerAccountId}}”登录。如果您需要重新绑定 {{provider}} 账户到当前账户，请确保 {{provider}} 账户的邮件地址为 {{email}} ，我们会在登陆时为你自动绑定到当前登录账户。',
        forbidden: '您至少需要保留一个第三方账户绑定。',
        title: '是否解绑该第三方账户 {{provider}} ？',
      },
    },
    username: '用户名',
  },
  signout: '退出登录',
  signup: '注册',
  stats: {
    aiheatmaps: 'AI 指数',
    assistants: '助手数',
    assistantsRank: {
      left: '助手名称',
      right: '话题数',
      title: '助手使用率',
    },
    createdAt: '用户创建于',
    days: '天',
    empty: {
      desc: '请积累更多聊天数据后查看',
      title: '暂无数据',
    },
    lastYearActivity: '过去一年活跃度',
    loginGuide: {
      f1: '获取免费用量',
      f2: '多端同步消息',
      f3: '拥有丰富助手',
      f4: '探索强大插件',
      title: '登陆后你可以：',
    },
    messages: '消息数',
    modelsRank: {
      left: '模型名称',
      right: '消息数',
      title: '模型使用率',
    },
    share: {
      title: '我的 AI 活跃指数',
    },
    topics: '话题数',
    topicsRank: {
      left: '话题名称',
      right: '消息数',
      title: '话题内容量',
    },
    updatedAt: '数据更新至',
    welcome: '{{username}}, 这是你和 {{appName}} 相伴的第 <span>{{days}}</span> 天',
    words: '累计字数',
  },
  tab: {
    apikey: 'API Key 管理',
    profile: '个人资料',
    security: '安全',
    stats: '数据统计',
  },
};
